backend:
  name: github
  repo: boydivane007-hub/C-line- 
  branch: main
  base_url: https://decap-cms-oauth-provider.netlify.app 

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
    - name: "menu"
    label: "Menu Restaurant Céline"
    folder: "data"
    create: false
    slug: "menu"
    extension: "json"
    fields:
            - label: "Restaurant"
        name: "restaurant"
        widget: "list"
        summary: "{{fields.nom}} - {{fields.prix}} FCFA"
        fields:
                    - {label: "Nom du Plat", name: "nom", widget: "string"}
                    - {label: "Prix FCFA", name: "prix", widget: "number"}
                    - {label: "Description", name: "desc", widget: "text", required: false}
            - label: "Pizzeria"
        name: "pizzeria"
        widget: "list"
        summary: "{{fields.nom}} - {{fields.prix}} FCFA"
        fields:
                    - {label: "Nom de la Pizza", name: "nom", widget: "string"}
                    - {label: "Prix FCFA", name: "prix", widget: "number"}
            - label: "Glacier"
        name: "glacier"
        widget: "list"
        summary: "{{fields.nom}} - {{fields.prix}} FCFA"
        fields:
                    - {label: "Nom de la Glace", name: "nom", widget: "string"}
                    - {label: "Prix FCFA", name: "prix", widget: "number"}
                    - {label: "Image", name: "image", widget: "image", required: false}
